default: &default
   adapter: postgresql
   encoding: unicode
  
development:
   adapter: postgresql
   encoding: unicode
   database: <dbname>_development
   username: <username>
   password: <password>
   host: localhost
   port: 5432

test:
   adapter: postgresql
   encoding: unicode
   database: <dbname>_test
   username: <username>
   password: <password>
   host: localhost
   port: 5432
 
production:
   adapter: postgresql
   encoding: unicode
   database: <dbname>_production
   username: <username>
   password: <password>
   host: localhost
   port: 5432